package constants

// 日志格式模板集中定义，业务字段变更必须同步修改对应模板与调用处。
const (
	LogUserRegistered      = "用户注册成功: username=%s real_name=%s role=%s"
	LogUserLogin           = "用户登录成功: username=%s role=%s"
	LogUserLoginFailed     = "用户登录失败: username=%s reason=%s"
	LogUserDisabled        = "用户被禁用: username=%s operator=%s"
	LogUserUpdated         = "用户信息更新: user_id=%d username=%s role=%s"
	LogUserDeleted         = "用户删除: user_id=%d username=%s operator=%s"
	LogDeviceCreated       = "设备入台账: device_id=%d asset_code=%s name=%s department=%s status=%s"
	LogDeviceUpdated       = "设备更新: device_id=%d name=%s status=%s"
	LogDeviceDisabled      = "设备禁用: device_id=%d asset_code=%s operator=%s"
	LogDeviceEnabled       = "设备启用: device_id=%d asset_code=%s operator=%s"
	LogDeviceStatusChanged = "设备状态变更: device_id=%d from=%s to=%s"
	LogPurchaseCreated     = "采购申请提交: request_no=%s department=%s device_name=%s status=%s"
	LogPurchaseAdminApprove = "设备科审核通过: request_no=%s approver=%s status=%s"
	LogPurchaseAdminReject = "设备科驳回: request_no=%s approver=%s comment=%s"
	LogPurchaseDeanApprove = "院长审批通过: request_no=%s approver=%s status=%s"
	LogPurchaseDeanReject  = "院长驳回: request_no=%s approver=%s comment=%s"
	LogPurchaseDelivered   = "采购到货登记: request_no=%s status=%s"
	LogPurchaseAccepted    = "采购验收通过并生成设备: request_no=%s device_id=%d asset_code=%s barcode=%s"
	LogMaintenanceCreated  = "保养/维修工单创建: record_no=%s device_id=%d type=%s status=%s"
	LogMaintenanceStarted  = "保养/维修开始执行: record_no=%s engineer=%s status=%s"
	LogMaintenanceCompleted = "保养/维修完成: record_no=%s device_id=%d cost=%.2f status=%s"
	LogMaintenanceCancelled = "保养/维修取消: record_no=%s reason=%s status=%s"
	LogCalibrationCreated  = "计量台账建立: instrument_no=%s device_id=%d cycle_months=%d status=%s"
	LogCalibrationResult   = "计量结果登记: instrument_no=%s result=%s status=%s device_id=%d"
	LogTransferCreated     = "调拨申请提交: transfer_no=%s device_id=%d from=%s to=%s status=%s"
	LogTransferApproved    = "调拨审批通过并更新科室: transfer_no=%s device_id=%d to_department=%s"
	LogTransferRejected    = "调拨驳回: transfer_no=%s approver=%s comment=%s"
	LogScrapCreated        = "报废申请提交: scrap_no=%s device_id=%d status=%s"
	LogScrapApproved       = "报废审批通过并归档: scrap_no=%s device_id=%d status=%s"
	LogScrapRejected       = "报废驳回: scrap_no=%s approver=%s comment=%s"
	LogAuditListed         = "审计日志查询: operator=%s page=%d page_size=%d"
	LogRateLimited         = "请求触发限流: ip=%s path=%s"
	LogDBInitFailed        = "数据库初始化失败: err=%v"
	LogServerStarted       = "服务启动成功: port=%s mode=%s"
	LogPanicRecovered      = "请求发生panic: path=%s request_id=%s err=%v"
	LogRequestHandled      = "请求处理完成: method=%s path=%s status=%d request_id=%s"
)
